### ISSUE TITLE
Safari Mobile scrolling not smooth

### ISSUE THREAD

**Issue by nio89** [christophery/pushy#71]
There seems to be a bug on Mobile Safari. Scrolling the main content isn't smooth - it stops scrolling immediately. Eventhough scrolling the Pushy Nav is working correctly. I've tried adding -webkit-overflow-scrolling: touch; to main content with no results.

You can check it out on your latest demo.

**Comment by jonom** [comment]
Are you using this rule as recommended in ReadMe to prevent scrolling?
```css
html, body{
    height: 100%;
    overflow-x: hidden;
}
```

Adding `-webkit-overflow-scrolling: touch` to that rule fixed the issue for me. The example in ReadMe should probably be updated to below:

```css
html, body{
    height: 100%;
    overflow-x: hidden;
    -webkit-overflow-scrolling: touch;
}
```
